// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8VmlN-n63kI_SbPomj1DHxDi8a_L7_cg',
    appId: '1:891282271518:web:e20ed4f84f3f88e08ead0f',
    messagingSenderId: '891282271518',
    projectId: 'assignment-project-2473b',
    authDomain: 'assignment-project-2473b.firebaseapp.com',
    storageBucket: 'assignment-project-2473b.appspot.com',
    measurementId: 'G-G9E5JZ3V8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6nX4JwJ41FibHkfQ-voO57l1U8HHohmQ',
    appId: '1:891282271518:android:f472128373aea39c8ead0f',
    messagingSenderId: '891282271518',
    projectId: 'assignment-project-2473b',
    storageBucket: 'assignment-project-2473b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPkUsjL_0d_gpk5y2lVp0TIX3QC36o_YY',
    appId: '1:891282271518:ios:ad8ec5d7ff720d088ead0f',
    messagingSenderId: '891282271518',
    projectId: 'assignment-project-2473b',
    storageBucket: 'assignment-project-2473b.appspot.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPkUsjL_0d_gpk5y2lVp0TIX3QC36o_YY',
    appId: '1:891282271518:ios:ad8ec5d7ff720d088ead0f',
    messagingSenderId: '891282271518',
    projectId: 'assignment-project-2473b',
    storageBucket: 'assignment-project-2473b.appspot.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8VmlN-n63kI_SbPomj1DHxDi8a_L7_cg',
    appId: '1:891282271518:web:67429af4dc49f9588ead0f',
    messagingSenderId: '891282271518',
    projectId: 'assignment-project-2473b',
    authDomain: 'assignment-project-2473b.firebaseapp.com',
    storageBucket: 'assignment-project-2473b.appspot.com',
    measurementId: 'G-DK39NYDBG0',
  );
}
